export const websocketEventNames: Record<string, string> = {
	UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
	UPDATE_GAME_STATE: 'UPDATE_GAME_STATE',
	SEND_INVITE_TO_FRIENDSHIP: 'SEND_INVITE_TO_FRIENDSHIP',
	INVITE_TO_GAME: 'INVITE_TO_GAME',
	INVITE_TO_GAME_IS_ACCEPTED: 'INVITE_TO_GAME_IS_ACCEPTED',
	INVITATION_TO_GAME_HAS_BEEN_SENT: 'INVITATION_TO_GAME_HAS_BEEN_SENT',
	INVITE_TO_GAME_IS_CANCELLED: 'INVITE_TO_GAME_IS_DECLINE',
	USER_IS_NOT_ONLINE: 'USER_IS_NOT_ONLINE',
};
